from project_euler.geometry.geometry import is_pentagonal, is_hexagonal, triangular

from project_euler.utils.timeit import timeit


@timeit
def problem45():
    """
    Triangular, pentagonal, and hexagonal
    Problem 45

    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

        Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
        Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
        Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.
    """
    n = 0
    while True:
        t = triangular(n)
        if is_pentagonal(t) and is_hexagonal(t):
            if n > 285:
                break
        n += 1
    return t


problem45()
